#!/bin/bash

echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
whoami
pushd $REPO
source /home/ubuntu/.nvm/nvm.sh && nvm install && npm install && npm run build
popd

cp -a $REPO ./build/

${PIP} install -r $REPO/requirements/requirements.txt
