#!/bin/bash

echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
whoami
pushd $REPO
su - ubuntu -c "source /home/ubuntu/.nvm/nvm.sh" && nvm install && npm install && npm run build
popd

cp -a $REPO ./build/

${PIP} install -r $REPO/requirements/requirements.txt
